### ISSUE TITLE
Log forwarding is not working on manually created log groups

### ISSUE THREAD

**Issue by sema4-fgulmammadli** [amplify-education/serverless-log-forwarding#75]
I have this configuration in my serverless,yaml:

```
provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-log-forwarding

custom:
  logForwarding:
    destinationARN: <arn to lambda>

resources:
  Resources:
    MyCustomLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: MyCustomLogGroup
        RetentionInDays: 90
```
I can succesfully deploy this to aws but I cant see the lambda in subscription filter of log group. 
Does the plugin work only on automatically created log groups from functions?
